use dds::{ColorFormat, Format};

pub const ALL_FORMATS: &[Format] = &[
    // uncompressed formats
    Format::R8G8B8_UNORM,
    Format::B8G8R8_UNORM,
    Format::R8G8B8A8_UNORM,
    Format::R8G8B8A8_SNORM,
    Format::B8G8R8A8_UNORM,
    Format::B8G8R8X8_UNORM,
    Format::B5G6R5_UNORM,
    Format::B5G5R5A1_UNORM,
    Format::B4G4R4A4_UNORM,
    Format::A4B4G4R4_UNORM,
    Format::R8_SNORM,
    Format::R8_UNORM,
    Format::R8G8_UNORM,
    Format::R8G8_SNORM,
    Format::A8_UNORM,
    Format::R16_UNORM,
    Format::R16_SNORM,
    Format::R16G16_UNORM,
    Format::R16G16_SNORM,
    Format::R16G16B16A16_UNORM,
    Format::R16G16B16A16_SNORM,
    Format::R10G10B10A2_UNORM,
    Format::R11G11B10_FLOAT,
    Format::R9G9B9E5_SHAREDEXP,
    Format::R16_FLOAT,
    Format::R16G16_FLOAT,
    Format::R16G16B16A16_FLOAT,
    Format::R32_FLOAT,
    Format::R32G32_FLOAT,
    Format::R32G32B32_FLOAT,
    Format::R32G32B32A32_FLOAT,
    Format::R10G10B10_XR_BIAS_A2_UNORM,
    Format::AYUV,
    Format::Y410,
    Format::Y416,
    // sub-sampled formats
    Format::R1_UNORM,
    Format::R8G8_B8G8_UNORM,
    Format::G8R8_G8B8_UNORM,
    Format::UYVY,
    Format::YUY2,
    Format::Y210,
    Format::Y216,
    // bi-planar formats
    Format::NV12,
    Format::P010,
    Format::P016,
    // block compression formats
    Format::BC1_UNORM,
    Format::BC2_UNORM,
    Format::BC2_UNORM_PREMULTIPLIED_ALPHA,
    Format::BC3_UNORM,
    Format::BC3_UNORM_PREMULTIPLIED_ALPHA,
    Format::BC4_UNORM,
    Format::BC4_SNORM,
    Format::BC5_UNORM,
    Format::BC5_SNORM,
    Format::BC6H_UF16,
    Format::BC6H_SF16,
    Format::BC7_UNORM,
    // ASTC formats
    Format::ASTC_4X4_UNORM,
    Format::ASTC_5X4_UNORM,
    Format::ASTC_5X5_UNORM,
    Format::ASTC_6X5_UNORM,
    Format::ASTC_6X6_UNORM,
    Format::ASTC_8X5_UNORM,
    Format::ASTC_8X6_UNORM,
    Format::ASTC_8X8_UNORM,
    Format::ASTC_10X5_UNORM,
    Format::ASTC_10X6_UNORM,
    Format::ASTC_10X8_UNORM,
    Format::ASTC_10X10_UNORM,
    Format::ASTC_12X10_UNORM,
    Format::ASTC_12X12_UNORM,
    // non-standard formats
    Format::BC3_UNORM_RXGB,
    Format::BC3_UNORM_NORMAL,
];

pub const ALL_COLORS: &[ColorFormat] = &[
    ColorFormat::ALPHA_U8,
    ColorFormat::GRAYSCALE_U8,
    ColorFormat::RGB_U8,
    ColorFormat::RGBA_U8,
    ColorFormat::ALPHA_U16,
    ColorFormat::GRAYSCALE_U16,
    ColorFormat::RGB_U16,
    ColorFormat::RGBA_U16,
    ColorFormat::ALPHA_F32,
    ColorFormat::GRAYSCALE_F32,
    ColorFormat::RGB_F32,
    ColorFormat::RGBA_F32,
];
